- project:
    check:
      jobs:
        - tox-py27:
            required-projects:
              - name: github.com/ansible-network/network-engine
        - tox-py36:
            required-projects:
              - name: github.com/ansible-network/network-engine
    gate:
      jobs:
        - tox-py27:
            required-projects:
              - name: github.com/ansible-network/network-engine
        - tox-py36:
            required-projects:
              - name: github.com/ansible-network/network-engine
